services:
  mysql:
    image: mysql:8.0
    container_name: ecodeli_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_root_password
      MYSQL_DATABASE: ecodeli
      MYSQL_USER: ecodeli_user
      MYSQL_PASSWORD: your_strong_user_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecodeli_net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ecodeli_api
    environment:
      DB_HOST: mysql
      DB_USER: ecodeli_user
      DB_PASSWORD: your_strong_user_password
      DB_NAME: ecodeli
      API_PORT: 3002
    depends_on:
      - mysql
    networks:
      - ecodeli_net

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: ecodeli_front
    environment:
      VITE_API_URL: http://ecodeli_api:3002
    depends_on:
      - api
    networks:
      - ecodeli_net

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: ecodeli_admin
    environment:
      VITE_API_URL: http://ecodeli_api:3002
    depends_on:
      - api
    networks:
      - ecodeli_net

  nginx:
    image: nginx:stable-alpine
    container_name: ecodeli_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    depends_on:
      - front
      - admin
      - api
    networks:
      - ecodeli_net

volumes:
  mysql_data:

networks:
  ecodeli_net:
    driver: bridge