version: '3.9'

services:
  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "3000:3000"
    restart: always

  admin:
    build:
      context: .
      dockerfile: admin/Dockerfile
    ports:
      - "3001:3000"
    restart: always

  api:
    build: ./api
    container_name: ecodeli_api
    ports:
      - "3002:3002"
    env_file:
      - ./api/.env
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql:
    image: mysql:8.0
    container_name: ecodeli_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root-ecodeli-1234
      MYSQL_DATABASE: ecodeli
      MYSQL_USER: dev-admin
      MYSQL_PASSWORD: dev:sandrine
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  nginx:
    image: nginx:alpine
    container_name: ecodeli_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
      - admin
      - api
    restart: always
