services:
  front:
    build: ./front
    container_name: ecodeli_front
    ports:
      - "3000:3000"
    restart: always

  admin:
    build: ./admin
    container_name: ecodeli_admin
    ports:
      - "3001:3000"
    restart: always

  api:
    build: ./api
    container_name: ecodeli_api
    ports:
      - "3002:3002"
    env_file:
      - ./api/.env
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: ecodeli_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecodeli
      MYSQL_USER: ecodeli_user
      MYSQL_PASSWORD: secret123
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always


  nginx:
    image: nginx:alpine
    container_name: ecodeli_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
      - admin
      - api
    restart: always
