version: "3.8"

services:
  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    container_name: ecodeli_front
    ports:
      - "3000:3000"
    depends_on:
      - admin
    networks:
      - ecodeli_net

  admin:
    build:
      context: .
      dockerfile: admin/Dockerfile
    container_name: ecodeli_admin
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - ecodeli_net

  mysql:
    image: mysql:8.0
    container_name: ecodeli_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecodeli
      MYSQL_USER: ecodeli_user
      MYSQL_PASSWORD: ecodeli_pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecodeli_net

  nginx:
    image: nginx:alpine
    container_name: ecodeli_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
    networks:
      - ecodeli_net

volumes:
  mysql_data:

networks:
  ecodeli_net:
    external: true
