services:
  mysql:
    image: mysql:8.0
    container_name: ecodeli_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root-242
      MYSQL_DATABASE: ecodeli
      MYSQL_USER: dev-admin
      MYSQL_PASSWORD: dev_sandrine
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ecodeli_net

  api:
    image: ecodeli_api
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: ecodeli_api
    environment:
      DB_HOST: mysql
      DB_USER: dev-admin
      DB_PASSWORD: dev_sandrine
      DB_NAME: ecodeli
      API_PORT: 3002
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    networks:
      - ecodeli_net

  front:
    image: ecodeli_front
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    container_name: ecodeli_front
    ports:
      - "3000:3000"
    networks:
      - ecodeli_net

  admin:
    image: ecodeli_admin
    build:
      context: ./admin
      dockerfile: Dockerfile.prod
    container_name: ecodeli_admin
    ports:
      - "3001:3001"
    networks:
      - ecodeli_net

  nginx:
    image: nginx:stable-alpine
    container_name: ecodeli_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - front
      - admin
      - api
    networks:
      - ecodeli_net

volumes:
  mysql_data:

networks:
  ecodeli_net:
    driver: bridge
