FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

RUN npm install -g nodemon
RUN npm install --save-dev nodemon
RUN npm install morgan
RUN npm install node-fetch

COPY . .

CMD ["npm", "run", "dev"]