GET http://localhost:3002/provider/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm1haWwiOiJha291YWxhYjVAZ21haWwuY29tIiwicm9sZSI6InByb3ZpZGVyIiwidGltZXN0YW1wIjoxNzUzMzQ4NDAzMTY0LCJpYXQiOjE3NTMzNDg0MDMsImV4cCI6MTc1MzM1NTYwM30.BH6z2cny_ZAzanP2vdZPl70RGxsINzkUzh5vaUC7JL8
