### TEST CREATION PROVIDER
GET http://localhost:3002/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm1haWwiOiJ0ZXN0QGljbG91ZC5jb20iLCJyb2xlIjoicHJvdmlkZXIiLCJ0aW1lc3RhbXAiOjE3NTE1MzM1MjE2NjEsImlhdCI6MTc1MTUzMzUyMSwiZXhwIjoxNzUxNTQwNzIxfQ.uBGSWvLmOP07EN0Z4KSAQQRaHraYi2vExxeYcXC4QZo
Content-Type: application/json
