### TEST CREATION PROVIDER
GET http://localhost:3002/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm1haWwiOiJ0ZXN0QGljbG91ZC5jb20iLCJyb2xlIjoicHJvdmlkZXIiLCJ0aW1lc3RhbXAiOjE3NTE1MzE4NDE1MzYsImlhdCI6MTc1MTUzMTg0MSwiZXhwIjoxNzUxNTM5MDQxfQ.Hky-KnfPmoPpKxO-SHnuWvEjgN8lfzAGudfRaEMHiBs
Content-Type: application/json
