### TEST CREATION PROVIDER
GET http://localhost:3002/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm1haWwiOiJ0ZXN0QGljbG91ZC5jb20iLCJyb2xlIjoicHJvdmlkZXIiLCJ0aW1lc3RhbXAiOjE3NTEyNzE4Nzg5NTAsImlhdCI6MTc1MTI3MTg3OCwiZXhwIjoxNzUxMjc5MDc4fQ.8xXGxVgVxCqzs637naau7einChEy5Oa8tmxasOXRKsg
Content-Type: application/json


