
GET http://localhost:3002/shopowner-requests/available
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM4LCJtYWlsIjoiamVnaWNlMzYxOEBkb3NvbmV4LmNvbSIsInJvbGUiOiJkZWxpdmVyeS1kcml2ZXIiLCJ0aW1lc3RhbXAiOjE3NTMyMDAwNTk4ODYsImlhdCI6MTc1MzIwMDA1OSwiZXhwIjoxNzUzMjA3MjU5fQ.PeNu9oTFVaNEFCnfegrNEvf8zagug7aFqoKKDHPwfGQ
Content-Type: application/json
