### TEST CREATION PROVIDER
POST http://localhost:3002/requests/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm1haWwiOiJ0ZXN0QGljbG91ZC5jb20iLCJyb2xlIjoicHJvdmlkZXIiLCJ0aW1lc3RhbXAiOjE3NTE1MzE4NDE1MzYsImlhdCI6MTc1MTUzMTg0MSwiZXhwIjoxNzUxNTM5MDQxfQ.Hky-KnfPmoPpKxO-SHnuWvEjgN8lfzAGudfRaEMHiBs
Content-Type: application/json

{
  "type": "colis_total",
  "titre": "Test sans image",
  "description": "Une belle box mystère",
  "longueur": 40,
  "largeur": 30,
  "poids": 5,
  "prix": 25,
  "prix_suggere": 20,
  "adresse_depart": "Nice",
  "adresse_arrivee": "Paris",
  "date_demande": "2025-07-01"
}
