### TEST CREATION PROVIDER
GET http://localhost:3002/requests/public
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm1haWwiOiJ0ZXN0QGljbG91ZC5jb20iLCJyb2xlIjoicHJvdmlkZXIiLCJ0aW1lc3RhbXAiOjE3NTEyODc0MjIzODQsImlhdCI6MTc1MTI4NzQyMiwiZXhwIjoxNzUxMjk0NjIyfQ.fODZQQdh00mgfA_4HboXZiQoplJCoMpvjsa6-Q5QfYI
Content-Type: application/json