### Test GET Mes Annonces (Shop Owner)
GET http://localhost:3002/shopowner-requests/mine
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJtYWlsIjoic2ViZWxlYmUuc2VAZ21haWwuY29tIiwicm9sZSI6InNob3Atb3duZXIiLCJ0aW1lc3RhbXAiOjE3NTMyOTkxNTY4NTAsImlhdCI6MTc1MzI5OTE1NiwiZXhwIjoxNzUzMzA2MzU2fQ.wuKHCou-kROtGR_NsCu1JjX9CrfTi1jSZSXwThZ2fYI
Content-Type: application/json
